### ISSUE TITLE
Incorrect header specified in libraries.properties

### ISSUE THREAD

**Issue by lewma** [sandeepmistry/arduino-OBD2#6]
The libraries.properties file looks fine here on github, however if you add this OBD2 library to an Arduino sketch using Tools -> Manage Libraries in the IDE, the library gets added fine however the include file is specified as ODB2.h ( not OBD2.h ).

The result is that the sketch will not compile as the incorrect header file is specified.

Just a heads up incase anyone else runs into this same exact issue.

**Comment by sandeepmistry** [comment]
I've tagged a new release which includes PR https://github.com/sandeepmistry/arduino-OBD2/pull/3 which corrects the file. It should be available in a hour or so once the Arduino Library manager scans the new tag.
